[package]
name = "toychip"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = "0.35.2"
thiserror = "1.0.37"
structopt = "0.3.26"
rand = "0.8.5"